Feature/100 quick reservation styling
ChargeHub-Stage/Charge-Hub pull request #102
Opened 2024-04-02 09:56 UTC by Yarin18

2024-04-03 12:52 UTC, DanneD-Wisemen requested changes

2024-04-03 12:52 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/Timeslot.kt
>              .height(82.dp)
Don't define heights like this. Maybe I looked over those in previous PR's but these heights should all be wrapping the content so that when the fontsize is upped, the view scales along and the text is not cut off. Check your code for these issues

2024-04-03 12:52 UTC, DanneD-Wisemen commented on shared/src/commonMain/kotlin/db/repository/FirebaseRepository.kt
> +    //val firebaseUser: FirebaseUser?
Commented code

2024-04-03 12:52 UTC, DanneD-Wisemen commented on shared/src/commonMain/kotlin/db/repository/FirebaseRepository.kt
> +    fun getCurrentUserUid(): String = auth.currentUser?.uid ?: "Null"
String "Null"?

2024-04-03 12:52 UTC, DanneD-Wisemen commented on shared/src/commonMain/kotlin/screens/quickreservation/QuickReservationScreenUiState.kt
> +        for (i in 0..15) {
What is this 15? Maybe extract it to a constant

2024-04-03 12:52 UTC, DanneD-Wisemen commented on shared/src/commonMain/kotlin/screens/quickreservation/QuickReservationScreenViewModel.kt
> +
excess whitespacing

2024-04-10 10:15 UTC, Yarin18 commented on shared/src/commonMain/kotlin/screens/quickreservation/QuickReservationScreenUiState.kt
> +        for (i in 0..15) {
This was just for debugging purposes so I could see what it would look like when reservations are retrieved from the database. Will remove

2024-04-14 10:33 UTC, DanneD-Wisemen requested changes

2024-04-14 10:33 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/Timeslot.kt
>              .height(82.dp)
Have u checked this?

2024-04-14 10:33 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/screens/QuickReservationScreen.kt
> +
Excess whitespace

2024-04-14 10:33 UTC, DanneD-Wisemen commented on iosApp/iosApp/components/Timeslot.swift
> +            )
move this to the line above

2024-04-14 10:33 UTC, DanneD-Wisemen commented on shared/src/commonMain/kotlin/screens/login/LoginScreenUiState.kt
> +    var email: String = "yarin@gmail.com",
This should not be pushed, unless you check if it's a debug build first

2024-04-15 07:03 UTC, Yarin18 commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/Timeslot.kt
>              .height(82.dp)
I sent you a private message about this on slack, not entirely sure how to solve this as wrapContentHeight does not work.

2024-04-15 07:30 UTC, DanneD-Wisemen approved these changes

2024-04-15 07:32 UTC, DanneD-Wisemen requested changes

2024-04-15 07:32 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/Timeslot.kt
>              .height(82.dp)
If this is fixed with the constraint this is ready to merge!

2024-04-15 08:22 UTC, merged