edit text, email field and password field
ChargeHub-Stage/Charge-Hub pull request #59
Opened 2024-03-15 12:07 UTC by Yarin18

2024-03-19 12:01 UTC, DanneD-Wisemen requested changes

2024-03-19 12:01 UTC, DanneD-Wisemen commented on composeApp/src/main/res/values/strings.xml
> +    <string name="password_is_required">" 'Password cannot be empty'"</string>
I think something went wrong with these quotation marks

2024-03-19 12:01 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/TextFields.kt
> +                Spacer(modifier = Modifier.padding(top = 5.dp))
I think this padding could be added to the row itself so you don't need an extra spacer, correct me if I'm wrong

2024-03-19 12:41 UTC, Yarin18 commented on composeApp/src/main/res/values/strings.xml
> +    <string name="password_is_required">" 'Password cannot be empty'"</string>
I meant to do them this way, but the closing quotation should only be behind 'password', so I changed that

2024-03-25 00:47 UTC, DanneD-Wisemen approved these changes

2024-03-25 07:43 UTC, merged