ios component that shows next reservation
ChargeHub-Stage/Charge-Hub pull request #88
Opened 2024-03-27 11:38 UTC by sebastian-vangrieken

2024-04-03 10:51 UTC, DanneD-Wisemen requested changes

2024-04-03 10:51 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/NextReservationComponent.kt
Never use your component directly in your preview!

2024-04-03 10:51 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/NextReservationComponent.kt
> +            Box {
Instead of these complicated nested rows and colums: take a look at this
https://developer.android.com/develop/ui/compose/layouts/constraintlayout

2024-04-03 10:51 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/NextReservationComponent.kt
> +            Box {
And try and split it up in the 3 info blocks: timeslot, start and location+date

2024-04-03 10:51 UTC, DanneD-Wisemen commented on iosApp/iosApp/components/NextReservation.swift
> +struct NextReservation: View {
Also try and split this up into multiple parts

2024-04-03 10:51 UTC, DanneD-Wisemen commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="timeslot">JOUW TIJDSLOT</string>
Preferably keep these uncapped and capitalize them in your presentation layer

2024-04-03 15:33 UTC, sebastian-vangrieken commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/NextReservationComponent.kt
> +            Box {
Yarin originally made the component for android, I just added the image in the background. I tried to recreate it as best as I could in a more readable way.

2024-04-14 10:07 UTC, DanneD-Wisemen requested changes

2024-04-14 10:07 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/NextReservationComponent.kt
> +//@Composable
Commented out code should not be merged

2024-04-14 10:07 UTC, DanneD-Wisemen commented on composeApp/src/androidMain/kotlin/com/wisemen/chargehub/ui/components/NextReservationComponent.kt
> +//@Composable
Commented out code should not be merged

2024-04-24 14:04 UTC, merged

2024-04-24 14:12 UTC, DanneD3 approved these changes