Feature/97 register info ios
ChargeHub-Stage/Charge-Hub pull request #98
Opened 2024-03-29 12:59 UTC by Yarin18

2024-04-03 12:40 UTC, DanneD-Wisemen requested changes

2024-04-03 12:40 UTC, DanneD-Wisemen commented on iosApp/iosApp/components/PagerView.swift
THis looks like its missing some indentations :)

2024-04-03 12:40 UTC, DanneD-Wisemen commented on iosApp/iosApp/components/PagerView.swift
> +    GeometryReader { geometry in
Just for some information, what does this GeometryReader do?

2024-04-03 12:40 UTC, DanneD-Wisemen commented on iosApp/iosApp/components/RegisterScreenComponents.swift
> +            Text(strings.get(id: SharedRes.strings().level_system_title, args: []))
Add a white line between components

2024-04-03 12:40 UTC, DanneD-Wisemen commented on iosApp/iosApp/components/RegisterScreenComponents.swift
Applicable for the whole file, add some whitespacing between parts

2024-04-03 12:40 UTC, DanneD-Wisemen commented on iosApp/iosApp/ui/pages/HomeScreen.swift
> +        Text("HomeScreen")
Hardcoded text

2024-04-03 12:40 UTC, DanneD-Wisemen commented on iosApp/iosApp/ui/pages/RegistrationScreen.swift
> +            } else if (currentRegisterState == CurrentRegisterState.info) {
See previous comments on this block

2024-04-03 12:40 UTC, DanneD-Wisemen commented on iosApp/iosApp/ui/pages/RegistrationScreen.swift
> +                    Text("This should not happen")
The app should crash in this place, try throwing an fatalerror()

2024-04-03 12:40 UTC, DanneD-Wisemen commented on iosApp/iosApp/ui/pages/RegistrationScreen.swift
> +                    Text("This should not happen")
https://cocoacasts.com/what-is-fatalerror-in-swift-and-when-to-use-it

2024-04-03 14:47 UTC, Yarin18 commented on iosApp/iosApp/components/PagerView.swift
> +    GeometryReader { geometry in
as far as I understand it its a tool that allows you to get information about the position and size of certain components which can be used to dynamic,ically calculate size of things

2024-04-03 14:51 UTC, DanneD-Wisemen commented on iosApp/iosApp/ui/pages/RegistrationScreen.swift
> +                    Text("This should not happen")
👆🏻

2024-04-03 14:53 UTC, DanneD-Wisemen requested changes

2024-04-03 14:53 UTC, DanneD-Wisemen commented on iosApp/iosApp/ui/pages/RegistrationScreen.swift
> +            EmailTextField(email:
weird indentation

2024-04-03 14:53 UTC, DanneD-Wisemen commented on iosApp/iosApp/ui/pages/RegistrationScreen.swift
> +            .alignmentGuide(.leading) { _ in 0 }
check indentation

2024-04-03 14:53 UTC, DanneD-Wisemen commented on iosApp/iosApp/ui/pages/RegistrationScreen.swift
> +                    Text("This should not happen")
fatalError() would be better

2024-04-07 16:11 UTC, DanneD-Wisemen approved these changes

2024-04-08 06:37 UTC, merged